<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotovoltaicSystem.Contracts\PhotovoltaicSystem.Contracts.csproj" />
    <ProjectReference Include="..\PhotovoltaicSystem\PhotovoltaicSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\SolarPanelCommand\NewFolder - Copia %282%29\" />
    <Folder Include="Commands\SolarPanelCommand\NewFolder - Copia\" />
  </ItemGroup>

</Project>
