// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhotovoltaicSystem.Persistence.Contexts;

#nullable disable

namespace PhotovoltaicSystem.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.Abstract.Housing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Housing", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.Inverter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("MaximumPower")
                        .HasColumnType("double precision");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PhotovoltaicSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Inverter", (string)null);
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.PhotovoltaicSystemInstall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasBattery")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HousingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InverterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HousingId")
                        .IsUnique();

                    b.HasIndex("InverterId");

                    b.ToTable("PhotovoltaicSystem", (string)null);
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.SolarPanel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotovoltaicSystemInstallId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhtovoltaicSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhotovoltaicSystemInstallId");

                    b.ToTable("SolarPanel", (string)null);
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.Building", b =>
                {
                    b.HasBaseType("PhotovoltaicSystem.Domain.Entities.Abstract.Housing");

                    b.Property<int>("NumberOfApartment")
                        .HasColumnType("integer");

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.House", b =>
                {
                    b.HasBaseType("PhotovoltaicSystem.Domain.Entities.Abstract.Housing");

                    b.ToTable("Houses", (string)null);
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.Abstract.Housing", b =>
                {
                    b.OwnsOne("PhotovoltaicSystem.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("HousingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("HousingId");

                            b1.ToTable("Housing");

                            b1.WithOwner()
                                .HasForeignKey("HousingId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.PhotovoltaicSystemInstall", b =>
                {
                    b.HasOne("PhotovoltaicSystem.Domain.Entities.Abstract.Housing", null)
                        .WithOne("PhotovoltaicSystem")
                        .HasForeignKey("PhotovoltaicSystem.Domain.Entities.PhotovoltaicSystemInstall", "HousingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhotovoltaicSystem.Domain.Entities.Inverter", "Inverter")
                        .WithMany()
                        .HasForeignKey("InverterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PhotovoltaicSystem.Domain.Records.MaintenanceRecord", "Maintenances", b1 =>
                        {
                            b1.Property<Guid>("PhotovoltaicSystemInstallId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("PhtovoltaicSystemId")
                                .HasColumnType("uuid");

                            b1.HasKey("PhotovoltaicSystemInstallId", "Id");

                            b1.ToTable("Maintenances");

                            b1.WithOwner()
                                .HasForeignKey("PhotovoltaicSystemInstallId");
                        });

                    b.Navigation("Inverter");

                    b.Navigation("Maintenances");
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.SolarPanel", b =>
                {
                    b.HasOne("PhotovoltaicSystem.Domain.Entities.PhotovoltaicSystemInstall", null)
                        .WithMany("SolarPanels")
                        .HasForeignKey("PhotovoltaicSystemInstallId");

                    b.OwnsOne("PhotovoltaicSystem.Domain.ValueObjects.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("SolarPanelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("SolarPanelId");

                            b1.ToTable("SolarPanel");

                            b1.WithOwner()
                                .HasForeignKey("SolarPanelId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.Building", b =>
                {
                    b.HasOne("PhotovoltaicSystem.Domain.Entities.Abstract.Housing", null)
                        .WithOne()
                        .HasForeignKey("PhotovoltaicSystem.Domain.Entities.Building", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.House", b =>
                {
                    b.HasOne("PhotovoltaicSystem.Domain.Entities.Abstract.Housing", null)
                        .WithOne()
                        .HasForeignKey("PhotovoltaicSystem.Domain.Entities.House", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.Abstract.Housing", b =>
                {
                    b.Navigation("PhotovoltaicSystem")
                        .IsRequired();
                });

            modelBuilder.Entity("PhotovoltaicSystem.Domain.Entities.PhotovoltaicSystemInstall", b =>
                {
                    b.Navigation("SolarPanels");
                });
#pragma warning restore 612, 618
        }
    }
}
